name: destin
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0-52.0.dev <4.0.0'

dependencies:
  camera: ^0.11.0+1
  camera_windows: ^0.2.1+8
  cloud_firestore: ^5.0.0
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  firebase_storage: ^12.0.0
  flutter:
    sdk: flutter
  flutter_slider_drawer: ^2.1.3
  google_sign_in: ^6.2.1
  http: ^1.2.1
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  percent_indicator: ^4.2.3
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  speech_to_text: ^6.5.1
  url_launcher: ^6.2.5
 
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon_assets/Bar.png
    - assets/icon_assets/threebar.png
    - assets/icon_assets/
    - assets/image_assets/designbackground.png
    - assets/image_assets/
    - assets/logos/Mobile_LoginPageLogo.png
    - assets/logos/
    - assets/Page_assets/
    - assets/stack_image/
    - assets/InterviewPage_stack_image/
  fonts:
    - family: Inter
      fonts:
      - asset: fonts\Inter-VariableFont_slnt,wght.ttf
        weight: 900
    
    - family: jetBrainsMono
      fonts:
      - asset: fonts\JetBrainsMono-VariableFont_wght.ttf
        weight: 900

