// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return android;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhFoN1NAynSJ9o4YCc3am3y3bp_duuJY8',
    appId: '1:807718658302:web:e15a6b1ac51974669a05af',
    messagingSenderId: '807718658302',
    projectId: 'destinx-c4de9',
    authDomain: 'destinx-c4de9.firebaseapp.com',
    databaseURL: 'https://destinx-c4de9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'destinx-c4de9.appspot.com',
    measurementId: 'G-Q9HFG8BBK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNk4Jr1en1XrriNK-5RuJ91R1LTBtbzPg',
    appId: '1:807718658302:android:3fd382eb72d21c3f9a05af',
    messagingSenderId: '807718658302',
    projectId: 'destinx-c4de9',
    databaseURL: 'https://destinx-c4de9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'destinx-c4de9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTiIKC66ihSGWxq-3cuZQI6z9BHIZSY6s',
    appId: '1:807718658302:ios:a53075f8fb46b0279a05af',
    messagingSenderId: '807718658302',
    projectId: 'destinx-c4de9',
    databaseURL: 'https://destinx-c4de9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'destinx-c4de9.appspot.com',
    iosBundleId: 'com.example.destin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTiIKC66ihSGWxq-3cuZQI6z9BHIZSY6s',
    appId: '1:807718658302:ios:7c5b8c532e5346879a05af',
    messagingSenderId: '807718658302',
    projectId: 'destinx-c4de9',
    databaseURL: 'https://destinx-c4de9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'destinx-c4de9.appspot.com',
    iosBundleId: 'com.example.destin.RunnerTests',
  );
}
